version: '3.8'

services:
  db:
    image: mariadb:10.11-alpine
    container_name: devjobs-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123!@#
      MYSQL_DATABASE: devjobs
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass123!
    volumes:
      - db_data:/var/lib/mysql
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=20
      - --innodb_buffer_pool_size=256M
    networks:
      - devjobs-network

  backend:
    build: .
    container_name: devjobs-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/devjobs?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass123!
      JAVA_OPTS: "-Xmx512m -Xms256m"
    depends_on:
      - db
    networks:
      - devjobs-network

volumes:
  db_data:

networks:
  devjobs-network:
    driver: bridge