spring:
  profiles:
    active: local

  # 데이터베이스 설정 (Docker의 MariaDB)
  datasource:
    url: jdbc:mariadb://localhost:3307/devjobs?useUnicode=true&characterEncoding=utf8
    username: devuser
    password: devpass
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop # 애플리케이션 실행 시 엔티티에 맞춰 DB 스키마 변경
    show-sql: true # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true

# 파일 업로드 경로
filepath: C:/uploadfile/

app:
  file:
    upload-dir: C:/uploadfile/

# 로깅 설정
logging:
  file:
    # 로그 파일을 저장할 경로와 이름
    name: logs/spring-boot.log
  level:
    # 루트 로깅 레벨을 INFO로 설정
    root: INFO
