spring:
  profiles:
    active: local

  # 데이터베이스 설정 (Docker의 MariaDB)
  datasource:
    url: jdbc:mariadb://localhost:3307/devjobs?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: devuser
    password: devpass
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 엔티티에 맞춰 DB 스키마 변경
    show-sql: false # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    
  # SQL 초기화 설정
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
      encoding: UTF-8
      
  # Spring Batch 설정
  batch:
    jdbc:
      initialize-schema: always # 배치 메타데이터 테이블 자동 생성
    job:
      enabled: false # 애플리케이션 시작 시 자동 실행 방지

# 파일 업로드 경로
filepath: C:/uploadfile/

app:
  file:
    upload-dir: C:/uploadfile/

# 로깅 설정
logging:
  file:
    # 로그 파일을 저장할 경로와 이름
    name: logs/spring-boot.log
  level:
    # 루트 로깅 레벨을 INFO로 설정
    root: INFO

jwt:
  secret: DevJobs123

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.example.devjobs
  paths-to-match: /api/**